# Generated by Django 2.2.6 on 2019-10-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='portions',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
