# Generated by Django 2.2.6 on 2019-10-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_portiondetails_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portiondetails',
            name='item',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='portiondetails',
            name='itemID',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='portiondetails',
            name='orderID',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
