# Generated by Django 2.2.6 on 2019-10-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_auto_20191030_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portiondetails',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PortionDetails_itemName', to='api_app.Item', to_field='name'),
        ),
    ]
